import Foundation

extension AgentAction {
  /// Korean label for progress lines; exhaustive so a new action cannot ship without one.
  var displayName: String {
    switch self {
    case .kakaoMessage: "카카오톡 전송"
    case .openApplication: "앱 열기"
    case .openProject: "프로젝트 열기"
    case .closeApplication: "앱 종료"
    case .browserSearch: "브라우저 검색"
    case .getActiveApplication: "현재 앱 확인"
    case .getSystemStatus: "Mac 상태 확인"
    case .listRunningApplications: "실행 중인 앱 확인"
    case .getClipboard: "클립보드 확인"
    case .setClipboard: "클립보드 변경"
    case .getServerStatus: "서버 상태 확인"
    case .getDockerContainers: "Docker 컨테이너 확인"
    case .getDockerLogs: "Docker 로그 확인"
    case .getServerProjectStatus: "서버 프로젝트 상태 확인"
    case .getRememberedProjectStatus, .getProjectHealth: "프로젝트 상태 확인"
    case .findProjectPath: "프로젝트 위치 찾기"
    case .getProjectGitStatus: "Git 상태 확인"
    case .getProjectBranch: "브랜치 확인"
    case .getProjectDiffSummary: "변경 내용 요약"
    case .getProjectRecentCommits: "최근 커밋 확인"
    case .getProjectChangedFiles: "변경 파일 확인"
    case .getProjectPackageScripts: "package 스크립트 확인"
    case .assessProjectDeploymentReadiness: "배포 준비 점검"
    case .runProjectTypecheck: "typecheck 실행"
    case .runProjectTests: "테스트 실행"
    case .runProjectLint: "lint 실행"
    case .runProjectBuild: "빌드 실행"
    case .startDevelopmentSession: "개발 세션 시작"
    case .endDevelopmentSession: "개발 세션 종료"
    case .getDevelopmentRecap: "최근 작업 요약"
    case .getTodayDevelopmentSummary: "오늘 작업 요약"
    case .getCodingAgentStatus: "코딩 에이전트 상태 확인"
    case .getCodingAgentRecentDiagnostics: "코딩 에이전트 진단"
    case .analyzeProjectWithCodingAgent: "Codex 코드 분석"
    case .proposeCodingTask: "코딩 작업 제안"
    case .executeCodingTask: "Codex 코드 수정"
    case .reviewCodingTaskResult: "코딩 결과 검토"
    case .verifyCodingTask: "코딩 결과 검증"
    case .rollbackCodingTask: "코딩 작업 되돌리기"
    case .discoverDevelopmentTask: "개발 작업 찾기"
    case .rankDevelopmentCandidates: "개발 작업 우선순위 정리"
    case .proposeDevelopmentTask: "개발 작업 제안"
    case .executeDevelopmentTask: "자율 개발 작업"
    case .verifyDevelopmentTask: "개발 작업 검증"
    case .repairDevelopmentTask: "개발 작업 복구"
    case .getAutonomousDevelopmentStatus: "자율 개발 상태 확인"
    case .inspectGitDiff: "Git 변경 확인"
    case .proposeCommitPlan: "커밋 계획 만들기"
    case .createCommit: "커밋 생성"
    case .getRemoteStatus: "원격 저장소 상태 확인"
    case .proposePush: "push 사전 확인"
    case .pushCurrentBranch: "push"
    case .getCIStatus: "CI 상태 확인"
    case .getPullRequestStatus: "PR 상태 확인"
    case .getGitWorkflowStatus: "Git 작업 상태 확인"
    case .captureScreen: "화면 캡처"
    case .inspectScreen: "화면 분석"
    case .inspectActiveWindow: "현재 창 분석"
    case .inspectScreenWithProjectContext: "화면과 프로젝트 함께 분석"
    case .getScreenAwarenessStatus: "화면 인식 상태 확인"
    case .getAIBackendStatus: "AI 백엔드 상태 확인"
    case .getRemoteControlStatus: "원격 제어 상태 확인"
    case .listVisibleWindows: "열린 창 확인"
    case .inspectWindow: "창 분석"
    case .getUIControlStatus: "UI 제어 상태 확인"
    case .getVSCodeQuickOpenStatus: "VS Code Quick Open 확인"
    case .activateApplication: "앱 앞으로 가져오기"
    case .focusWindow: "창 선택"
    case .closeWindow: "창 닫기"
    case .listUIElements: "UI 요소 확인"
    case .inspectUIElement: "UI 요소 살펴보기"
    case .pressUIElement: "버튼 누르기"
    case .focusUIElement: "UI 요소 선택"
    case .setUIText: "텍스트 입력"
    case .appendUIText: "텍스트 추가 입력"
    case .pressKeyboardShortcut: "단축키 누르기"
    case .scrollUI: "스크롤"
    case .selectMenuItem: "메뉴 선택"
    case .startDockerContainer: "컨테이너 시작"
    case .stopDockerContainer: "컨테이너 중지"
    case .restartDockerContainer: "컨테이너 재시작"
    case .answer: "답변"
    case .unknown: "알 수 없는 작업"
    }
  }
}
